// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXoDonSasIZ99RaZA69bnVTMIlH9nYEY',
    appId: '1:166629524832:web:64b4646483a335d885ca05',
    messagingSenderId: '166629524832',
    projectId: 'mapdatabase-f3797',
    authDomain: 'mapdatabase-f3797.firebaseapp.com',
    databaseURL: 'https://mapdatabase-f3797-default-rtdb.firebaseio.com',
    storageBucket: 'mapdatabase-f3797.appspot.com',
    measurementId: 'G-Y2W8NGQKXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOoGxWlgYEFg9LQUVieOITKZi27LQCGMg',
    appId: '1:166629524832:android:d2bccd985c1d58fb85ca05',
    messagingSenderId: '166629524832',
    projectId: 'mapdatabase-f3797',
    databaseURL: 'https://mapdatabase-f3797-default-rtdb.firebaseio.com',
    storageBucket: 'mapdatabase-f3797.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxBClyPyYcrjkuAyj06VfAVlua-qqXwS4',
    appId: '1:166629524832:ios:03c9c64f8bbc1ebc85ca05',
    messagingSenderId: '166629524832',
    projectId: 'mapdatabase-f3797',
    databaseURL: 'https://mapdatabase-f3797-default-rtdb.firebaseio.com',
    storageBucket: 'mapdatabase-f3797.appspot.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxBClyPyYcrjkuAyj06VfAVlua-qqXwS4',
    appId: '1:166629524832:ios:03c9c64f8bbc1ebc85ca05',
    messagingSenderId: '166629524832',
    projectId: 'mapdatabase-f3797',
    databaseURL: 'https://mapdatabase-f3797-default-rtdb.firebaseio.com',
    storageBucket: 'mapdatabase-f3797.appspot.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiXoDonSasIZ99RaZA69bnVTMIlH9nYEY',
    appId: '1:166629524832:web:33c0e72b370c708785ca05',
    messagingSenderId: '166629524832',
    projectId: 'mapdatabase-f3797',
    authDomain: 'mapdatabase-f3797.firebaseapp.com',
    databaseURL: 'https://mapdatabase-f3797-default-rtdb.firebaseio.com',
    storageBucket: 'mapdatabase-f3797.appspot.com',
    measurementId: 'G-B2LKQN562Z',
  );

}